### ISSUE TITLE
MITOS parallel

### ISSUE THREAD

**Issue by MarieLataretu** [MarieLataretu/mt#4]

**Comment by flomock** [comment]
Done

**Comment by MarieLataretu** [comment]
it doesn't work correclly with the small test example :/

it somehow takes always the same contig: `[spades, >NODE_2_length_9459_cov_22.570502], [soapdenovo2k57, >NODE_2_length_9459_cov_22.570502], [soapdenovo2k17, >NODE_2_length_9459_cov_22.570502]`

(soap contigs are names like `Contig42`)

**Comment by flomock** [comment]
fixed on dev_flo branch
